//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace NortHack
{
    using System;
    using System.Collections.Generic;
    
    public partial class Connection
    {
        public int Id { get; set; }
        public Nullable<int> IdeaID { get; set; }
        public Nullable<int> ProfileID { get; set; }
        public bool Likes { get; set; }
        public bool Follow { get; set; }
    
        public virtual Profile Profile { get; set; }
        public virtual Idea Idea { get; set; }
    }
}
